# Site settings
title:       Ricardo Magalhães
email:       magalhini@gmail.com
author:      Ricardo Magalhães
description: "The personal and work-life blog of Ricardo Magalhães"
baseurl:     ""
url:         "https://magalhini.github.io"
highlighter: pygments
timezone: Europe/Berlin
future: true

# Google analytics
google_analytics:

# Optional features
show_related_posts: true
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: magalhini
dribbble_username: magellan
twitter_username: magalhini
medium_id: magalhini
instagram_username: magalhini

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this article'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_tumblr: false
share_reddit: true
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: /post/:title
exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]
paginate: 4
sass:
  style: compressed
gems:
  - octopress-autoprefixer
  - jekyll-paginate
